name: nostr_notify
description: "Nostr notifications daemon for Linux desktop"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management & DI
  get: ^4.7.3

  # Nostr
  ndk: ^0.6.1-dev.6
  nostr_widgets: ^1.1.6

  # Notifications
  flutter_local_notifications: ^19.5.0

  # Database
  sembast: ^3.8.6
  path_provider: ^2.1.5
  path: ^1.9.1

  # Window management
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  flutter_single_instance: ^1.7.0
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.0
  system_theme: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    