name: noti
description: "Lightweight Nostr notifications - DMs, mentions, zaps, reposts & reactions"
publish_to: 'none'

version: 1.2.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.3
  ndk: 0.7.1-dev.0
  nostr_widgets: 1.2.1
  flutter_local_notifications: ^19.5.0
  sembast: ^3.8.6
  path_provider: ^2.1.5
  path: ^1.9.1
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  flutter_single_instance: ^1.7.0
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.0
  system_theme: ^3.2.0
  intl: any
  sembast_web: ^2.4.3
  web: ^1.1.1
  flutter_highlight: ^0.7.0
  sembast_cache_manager: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/notification.wav
    